# Generated by Django 5.1.3 on 2024-11-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('location_coors', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
            ],
        ),
    ]
